<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login_DDT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c0745af1-fadf-41a1-87ba-8c91bde3f190</testSuiteGuid>
   <testCaseLink>
      <guid>06ff6e18-bdb3-46db-985f-8642cb61f3f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Manual/Login/TC_Login with valid credential - DDT</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2cbeb1d7-7533-4fa9-a6af-cc0a40598a0f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/LoginData_Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2cbeb1d7-7533-4fa9-a6af-cc0a40598a0f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2cf3929d-9f05-4252-9a15-58b8806c4e51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2cbeb1d7-7533-4fa9-a6af-cc0a40598a0f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>b4d3affb-290b-45d2-864d-12bac7ad8b29</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
